### ISSUE TITLE
Raise AOI doesn't work

### ISSUE THREAD

**Issue by gisdirk** [joewdavies/geoblender#18]
Hi Joe, I tried to follow your instructions and made it to the last step. But failed to artificially 'raise' my AOI. As you can see in the attached image, the coastline is pretty flat. I am pretty sure I did something wrong but not sure what exactly. For this, I used Blender 4.0.2. Would be grateful if you could have a look and point me into the right direction.

![map](https://github.com/user-attachments/assets/cbd72461-85de-461d-b33d-cf194a6a0c50)

![Screenshot 2024-10-10 at 23 47 39](https://github.com/user-attachments/assets/3133ab4a-e1ca-4abf-a51d-463918ca683b)

**Comment by joewdavies** [comment]
Hi! It looks like a mismatch between your DEM and your mask. Make sure that you follow these steps for your mask: https://github.com/joewdavies/geoblender?tab=readme-ov-file#extra-mask-for-aoi-

For example i notice that your mask is also a tif, whereas mine was a png.

The displacement is working otherwise (you can see the shadows)
